### ISSUE TITLE
Prompt：你输出的计划必须将执行结果存储在一个变量 #E{n} 中，任务间的依赖关系可以在任务秒速中引用该变量来反应。

### ISSUE THREAD

**Issue by daoyuly** [arcstep/illufly#2]
任务秒速 是不是 任务描述？

**Comment by arcstep** [comment]
是的呢，感谢提醒 : )

https://github.com/arcstep/illufly/commit/9f7e0ca8e7f737b805e98a4414c4953d46ff51a3
