### ISSUE TITLE
TextEmbeddings 只可以是使用阿里云模型服务灵积API吗？

### ISSUE THREAD

**Issue by liangpn** [arcstep/illufly#3]
已经写好一个 怎么提pr

**Comment by arcstep** [comment]
已经支持的有：
    "ZhipuEmbeddings",
    "TextEmbeddings",
    "OpenAIEmbeddings",
    "HuggingFaceEmbeddings"

如果您愿意贡献更多的 Embeddings 可以参考  OpenAIEmbeddings 子类实现：https://github.com/arcstep/illufly/blob/c94e59b5989d8a2dfe43b6d3d3417a487012e9c9/illufly/community/openai/embeddings.py

**Comment by arcstep** [comment]
我也没有怎么提过 PR，不过你可以参考 AI 给出的回复，我问了 GPT 的结果是这样的：

> 在 GitHub 上提交修改请求（通常称为“Pull Request”）以合并到他人的项目中，您可以按照以下步骤进行：
> 
> 1. **Fork 项目**：
>    - 访问您想要贡献的项目的 GitHub 页面。
>    - 点击页面右上角的“Fork”按钮，将项目复制到您的 GitHub 账户中。
> 
> 2. **克隆 Fork 的项目**：
>    - 在您的 GitHub 账户中，找到刚刚 Fork 的项目。
>    - 点击“Code”按钮，复制项目的克隆 URL。
>    - 在本地计算机上打开终端或命令行，运行以下命令克隆项目：
>      ```bash
>      git clone <克隆 URL>
>      ```
>    - 进入项目目录：
>      ```bash
>      cd <项目目录>
>      ```
> 
> 3. **创建新分支**：
>    - 创建一个新分支来进行您的修改：
>      ```bash
>      git checkout -b <新分支名称>
>      ```
> 
> 4. **进行修改并提交**：
>    - 在本地编辑器中进行代码修改。
>    - 保存修改后，添加更改到暂存区：
>      ```bash
>      git add .
>      ```
>    - 提交更改：
>      ```bash
>      git commit -m "描述您的更改"
>      ```
> 
> 5. **推送到 GitHub**：
>    - 将您的分支推送到 GitHub：
>      ```bash
>      git push origin <新分支名称>
>      ```
> 
> 6. **创建 Pull Request**：
>    - 在 GitHub 上，访问您 Fork 的项目。
>    - 您会看到一个提示，询问是否要为刚刚推送的分支创建 Pull Request。点击“Compare & pull request”按钮。
>    - 在 Pull Request 页面，填写标题和描述，解释您的更改。
>    - 确认目标分支是原始项目的 `main` 或 `master` 分支（或其他适当的分支）。
>    - 点击“Create pull request”按钮提交请求。
> 
> 7. **等待反馈**：
>    - 项目维护者会审查您的 Pull Request。根据反馈，您可能需要进行进一步的修改。
> 
> 通过这些步骤，您就可以在 GitHub 上成功提交修改请求，并等待项目维护者的合并。
