### ISSUE TITLE
测试 ChatLearn 遇到 ValueError: <FLOW/Scribe> template_id not exist

### ISSUE THREAD

**Issue by liangpn** [arcstep/illufly#4]
这是我的代码

from illufly.learn import ChatLearn
from illufly.chat import ChatOpenAI
openai_model = os.getenv("OPENAI_MODEL")
talker = ChatLearn(ChatOpenAI(openai_model))
talker("我跟你说说我的女朋友")

这是报错信息：

Traceback (most recent call last):
  File "E:\localpath\test_RAG.py", line 64, in <module>
    talker = ChatLearn(ChatOpenAI(openai_model))
  File "E:\path\Anaconda\Anaconda2023\envs\illufly\lib\site-packages\illufly\core\runnable\agent\flow\chat_learn.py", line 54, in __init__
    scribe_template = scribe_template or PromptTemplate("FLOW/Scribe")
  File "E:\path\Anaconda\Anaconda2023\envs\illufly\lib\site-packages\illufly\core\runnable\prompt_template.py", line 37, in __init__
    self.text = load_prompt_template(template_id)
  File "E:\path\Anaconda\Anaconda2023\envs\illufly\lib\site-packages\illufly\hub\prompt.py", line 112, in load_prompt_template
    prompt_str = load_resource_template(template_id)
    prompt_str = load_resource_template(template_id)
  File "E:\path\Anaconda\Anaconda2023\envs\illufly\lib\site-packages\illufly\hub\prompt.py", line 37, in load_resource_template
    raise ValueError(f"<{template_id}> template_id not exist !")
ValueError: <FLOW/Scribe> template_id not exist !

**Comment by arcstep** [comment]
大概是 windows 和 mac 的包内资源路径表示方法有差异。

我修改了一个版本 v0.5.3 但手头暂时没有 windows 操作系统可以测试。
https://github.com/arcstep/illufly/commit/5d1653ec1339bbdb6e404aeb2fb545fbad155d37#diff-d29bb5f201c23990f2db0594b4a118ff7662d7dafc5a3d7d4f8aba4b33011de0R36

您如果急着测试可以拉取新的代码看看，我明天也找有 windows 的同事测试一下。

**Comment by liangpn** [comment]
> 大概是 windows 和 mac 的包内资源路径表示方法有差异。
> 
> 我修改了一个版本 v0.5.3 但手头暂时没有 windows 操作系统可以测试。 [5d1653e#diff-d29bb5f201c23990f2db0594b4a118ff7662d7dafc5a3d7d4f8aba4b33011de0R36](https://github.com/arcstep/illufly/commit/5d1653ec1339bbdb6e404aeb2fb545fbad155d37#diff-d29bb5f201c23990f2db0594b4a118ff7662d7dafc5a3d7d4f8aba4b33011de0R36)
> 
> 您如果急着测试可以拉取新的代码看看，我明天也找有 windows 的同事测试一下。

@arcstep 更新代码后，Windows测试正常了；另外 Linux上测试没问题

但后面的，
1.4 使用在对话中获得的经验，报异常

我的代码
embeddings = OpenAIEmbeddings(
    base_url=openai_embeddings_url,
    model=openai_embeddings_model,  
    dim=1024
)

db = FaissDB(embeddings=embeddings, top_k=3)
qwen = ChatOpenAI(openai_model, knowledge=[db])

qwen("你知道我女朋友叫什么吗？有什么爱好?")


对话已记录至对应的路径
![1730357236965](https://github.com/user-attachments/assets/18df4ca4-c2f0-439c-8ea7-353f88a74701)



[WARN] 读取文件失败 C:\Users\57247\AppData\Local\Temp\__ILLUFLY__\CHART_LEARN\356994-3865-0000.md: 'utf-8' codec can't decode byte 0xc4 in position 127: invalid continuation byte
[WARN] 读取文件失败 C:\Users\57247\AppData\Local\Temp\__ILLUFLY__\CHART_LEARN\356994-3865-0000.md: 'utf-8' codec can't decode byte 0xc4 in position 127: invalid continuation byte
[WARN] 读取文件失败 C:\Users\57247\AppData\Local\Temp\__ILLUFLY__\CHART_LEARN\356994-3865-0000.md: 'utf-8' codec can't decode byte 0xc4 in position 127: invalid continuation byte

作为AI助手，我并不了解你女朋友的具体信息，包括她的名字和爱好。保护个人隐私是非常重要的，我们都不应该未经对方同意就泄露这些信息。如果你愿意，你可以告诉我一些关于你女朋
友的兴趣爱好，我可以帮你提供一些建议或者想法，以便你们可以一起享受美好的时光。

**Comment by arcstep** [comment]
可能还是路径拼装的问题 : (

**Comment by arcstep** [comment]
可能问题出在这里。在之前的代码中，保存文件时没有指定 utf-8 编码，但在读取时统一使用了 utf-8 编码。
而 windows 的默认编码不是 utf-8 所以就会出错 : (

https://github.com/arcstep/illufly/blob/352928819249049e4d20d068c438fce75d7d866b/illufly/core/runnable/agent/flow/chat_learn.py#L29-L31

在 v0.5.6 的版本中我修复了这个地方。

**Comment by arcstep** [comment]
我在 v0.5.6 的版本中修复了这个地方。
